### PR TITLE
Yaml loader

### PR DESCRIPTION
**Pull request by stephanebisson**
YamlLoader works just like XmlLoader.

The goal is to be able to load tmsource yaml files directly without having to compile them to mapnik xml.

See https://phabricator.wikimedia.org/T192058#4175203 for how it all fits together.

### CODE REVIEW

**Comment by nyurik** [comment]
This looks very good, but why not use proper js class syntax? I'll review in depth soon

**Comment by stephanebisson** [comment]
@nyurik I started by copying XmlLoader and then s/xml/yaml so I didn't really think about that but I agree it should be considered as it would make a lot of code, not just in this repo, more compact and readable. I would prefer not to convert the style in this PR though.

**Comment by nyurik** [comment]
Thanks @stephanebisson, agree, makes sense.  The more fundamental issue is the usage.  XML needs to be modifiable because after it gets generated by mapcss -> xml converter, there are some things that need to be customized with the local settings, or perhaps some layers that should be dynamically removed.  Note that it is mapnik that requires everything to be in XML, not our preference. Why would we need this with yaml?  My understanding was that there needs to be a mapcss->xml converter built for kartotherian - something that most other code systems already support (e.g. Klokan's open tiles server).  That converter also generates XML internally, so we could still apply the existing settings & code to it.  Or am I missing something? CC: @pnorman

**Comment by stephanebisson** [comment]
@nyurik In this approach, the customization based on the source config (yamlSetDataSource, yamlSetParams, yamlLayers, yamlExceptLayers) is done on the yaml data before it is converted to xml by tilelive-tmsource.

**Comment by stephanebisson** [comment]
I've compared the XMLs generated on the fly with the ones pre-generated by some tool and saved into the repos.

tmsource: In the XML generated on the fly, every Layer node as 2 additional attributes: 
  `maximum-scale-denominator="1000000000"`
  `minimum-scale-denominator="100"`

tmstyle: In the XML generated on the fly, every Layer node as 1 additional attribute:
  `srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"`
Note that this attribute is identical to the srs attribute on the Map node in both XML documents.

**Comment by pnorman** [comment]
> tmsource: In the XML generated on the fly, every Layer node as 2 additional attributes:
> maximum-scale-denominator="1000000000"
> minimum-scale-denominator="100"
> 
> tmstyle: In the XML generated on the fly, every Layer node as 1 additional attribute:
> srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"

I wouldn't worry about either of these.

**Comment by pnorman** [comment]
> My understanding was that there needs to be a mapcss->xml converter built for kartotherian 

CartoCSS, not MapCSS, which is a different language

> - something that most other code systems already support (e.g. Klokan's open tiles server). That converter also generates XML internally, so we could still apply the existing settings & code to it. Or am I missing something? CC: @pnorman

See https://phabricator.wikimedia.org/T192058, but we're going to use [tlielive-tmstyle](https://github.com/mojodna/tilelive-tmstyle) and [tilelive-tmsource](https://github.com/mojodna/tilelive-tmsource). Both of these thinly wrap the XML-based tilelive providers, and convert to XML internally.

We could try to get in to the internals of those modules to access the XML, but it's better to modify the yaml.

**Review by pnorman — APPROVED** [review]
👍 , but I haven't done a detailed review of the code line-by-line since it's copying existing code.

**Pull request merged**
